// <auto-generated />
using System;
using LowCortisol.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LowCortisol.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("LowCortisol.Domain.Contexts.DeviceManagement.Aggregates.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_user_id");

                    b.HasKey("Id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.DeviceManagement.Entities.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("sensor_type");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("sensors", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.IdentityAccess.Aggregates.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.HasKey("Id");

                    b.ToTable("user_accounts", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.IncidentManagement.Aggregates.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<Guid>("ReportedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("reported_by_user_id");

                    b.HasKey("Id");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.IncidentManagement.Entities.IncidentHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("incident_id");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.ToTable("incident_history_entries", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.Monitoring.Aggregates.MonitoringSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at_utc");

                    b.HasKey("Id");

                    b.ToTable("monitoring_sessions", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.Monitoring.Entities.MonitoringEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<Guid>("MonitoringSessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("monitoring_session_id");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("MonitoringSessionId");

                    b.ToTable("monitoring_events", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.Monitoring.Entities.SensorReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<Guid>("MonitoringSessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("monitoring_session_id");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at_utc");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("sensor_id");

                    b.HasKey("Id");

                    b.HasIndex("MonitoringSessionId");

                    b.ToTable("sensor_readings", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.NotificationManagement.Aggregates.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("recipient_user_id");

                    b.HasKey("Id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.NotificationManagement.Entities.NotificationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("AttemptedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("attempted_at_utc");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("notification_id");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.ToTable("notification_attempts", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.Reporting.Aggregates.ConsumptionReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("generated_at_utc");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_user_id");

                    b.HasKey("Id");

                    b.ToTable("consumption_reports", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.Reporting.Entities.ReportLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ConsumptionReportId")
                        .HasColumnType("TEXT")
                        .HasColumnName("consumption_report_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.HasKey("Id");

                    b.HasIndex("ConsumptionReportId");

                    b.ToTable("report_lines", (string)null);
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.DeviceManagement.Aggregates.Device", b =>
                {
                    b.OwnsOne("LowCortisol.Domain.Contexts.DeviceManagement.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("TEXT")
                                .HasColumnName("location");

                            b1.HasKey("DeviceId");

                            b1.ToTable("devices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.OwnsOne("LowCortisol.Domain.Contexts.DeviceManagement.ValueObjects.DeviceStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("TEXT")
                                .HasColumnName("status");

                            b1.HasKey("DeviceId");

                            b1.ToTable("devices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.OwnsOne("LowCortisol.Domain.Contexts.DeviceManagement.ValueObjects.DeviceName", "Name", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("TEXT")
                                .HasColumnName("name");

                            b1.HasKey("DeviceId");

                            b1.ToTable("devices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.OwnsOne("LowCortisol.Domain.Contexts.DeviceManagement.ValueObjects.DeviceType", "Type", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("TEXT")
                                .HasColumnName("type");

                            b1.HasKey("DeviceId");

                            b1.ToTable("devices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.OwnsOne("LowCortisol.Domain.Contexts.DeviceManagement.ValueObjects.Threshold", "Threshold", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("threshold_unit");

                            b1.Property<decimal>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("threshold_value");

                            b1.HasKey("DeviceId");

                            b1.ToTable("devices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();

                    b.Navigation("Threshold");

                    b.Navigation("Type")
                        .IsRequired();
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.DeviceManagement.Entities.Sensor", b =>
                {
                    b.HasOne("LowCortisol.Domain.Contexts.DeviceManagement.Aggregates.Device", null)
                        .WithMany("Sensors")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LowCortisol.Domain.Contexts.DeviceManagement.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("SensorId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("TEXT")
                                .HasColumnName("location");

                            b1.HasKey("SensorId");

                            b1.ToTable("sensors");

                            b1.WithOwner()
                                .HasForeignKey("SensorId");
                        });

                    b.OwnsOne("LowCortisol.Domain.Contexts.DeviceManagement.ValueObjects.DeviceStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("SensorId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("TEXT")
                                .HasColumnName("status");

                            b1.HasKey("SensorId");

                            b1.ToTable("sensors");

                            b1.WithOwner()
                                .HasForeignKey("SensorId");
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.IdentityAccess.Aggregates.UserAccount", b =>
                {
                    b.OwnsOne("LowCortisol.Domain.Contexts.IdentityAccess.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(180)
                                .HasColumnType("TEXT")
                                .HasColumnName("email");

                            b1.HasKey("UserAccountId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("user_accounts");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("LowCortisol.Domain.Contexts.IdentityAccess.ValueObjects.PasswordHash", "PasswordHash", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("password_hash");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("user_accounts");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("LowCortisol.Domain.Contexts.IdentityAccess.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("TEXT")
                                .HasColumnName("name");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("user_accounts");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("LowCortisol.Domain.Contexts.IdentityAccess.ValueObjects.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("TEXT")
                                .HasColumnName("phone");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("user_accounts");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("LowCortisol.Domain.Contexts.IdentityAccess.ValueObjects.UserRole", "Role", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("TEXT")
                                .HasColumnName("role");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("user_accounts");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("PasswordHash")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();

                    b.Navigation("Role")
                        .IsRequired();
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.IncidentManagement.Aggregates.Incident", b =>
                {
                    b.OwnsOne("LowCortisol.Domain.Contexts.IncidentManagement.ValueObjects.IncidentDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("IncidentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("description");

                            b1.HasKey("IncidentId");

                            b1.ToTable("incidents");

                            b1.WithOwner()
                                .HasForeignKey("IncidentId");
                        });

                    b.OwnsOne("LowCortisol.Domain.Contexts.IncidentManagement.ValueObjects.IncidentSeverity", "Severity", b1 =>
                        {
                            b1.Property<Guid>("IncidentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("TEXT")
                                .HasColumnName("severity");

                            b1.HasKey("IncidentId");

                            b1.ToTable("incidents");

                            b1.WithOwner()
                                .HasForeignKey("IncidentId");
                        });

                    b.OwnsOne("LowCortisol.Domain.Contexts.IncidentManagement.ValueObjects.IncidentStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("IncidentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("TEXT")
                                .HasColumnName("status");

                            b1.HasKey("IncidentId");

                            b1.ToTable("incidents");

                            b1.WithOwner()
                                .HasForeignKey("IncidentId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Severity")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.IncidentManagement.Entities.IncidentHistoryEntry", b =>
                {
                    b.HasOne("LowCortisol.Domain.Contexts.IncidentManagement.Aggregates.Incident", null)
                        .WithMany("History")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.Monitoring.Entities.MonitoringEvent", b =>
                {
                    b.HasOne("LowCortisol.Domain.Contexts.Monitoring.Aggregates.MonitoringSession", null)
                        .WithMany("Events")
                        .HasForeignKey("MonitoringSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.Monitoring.Entities.SensorReading", b =>
                {
                    b.HasOne("LowCortisol.Domain.Contexts.Monitoring.Aggregates.MonitoringSession", null)
                        .WithMany("Readings")
                        .HasForeignKey("MonitoringSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LowCortisol.Domain.Contexts.Monitoring.ValueObjects.MeasurementUnit", "Unit", b1 =>
                        {
                            b1.Property<Guid>("SensorReadingId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("unit");

                            b1.HasKey("SensorReadingId");

                            b1.ToTable("sensor_readings");

                            b1.WithOwner()
                                .HasForeignKey("SensorReadingId");
                        });

                    b.OwnsOne("LowCortisol.Domain.Contexts.Monitoring.ValueObjects.ReadingValue", "Value", b1 =>
                        {
                            b1.Property<Guid>("SensorReadingId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("reading_value");

                            b1.HasKey("SensorReadingId");

                            b1.ToTable("sensor_readings");

                            b1.WithOwner()
                                .HasForeignKey("SensorReadingId");
                        });

                    b.OwnsOne("LowCortisol.Domain.Contexts.Monitoring.ValueObjects.SensorType", "SensorType", b1 =>
                        {
                            b1.Property<Guid>("SensorReadingId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("TEXT")
                                .HasColumnName("sensor_type");

                            b1.HasKey("SensorReadingId");

                            b1.ToTable("sensor_readings");

                            b1.WithOwner()
                                .HasForeignKey("SensorReadingId");
                        });

                    b.Navigation("SensorType")
                        .IsRequired();

                    b.Navigation("Unit")
                        .IsRequired();

                    b.Navigation("Value")
                        .IsRequired();
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.NotificationManagement.Aggregates.Notification", b =>
                {
                    b.OwnsOne("LowCortisol.Domain.Contexts.NotificationManagement.ValueObjects.NotificationStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("NotificationId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("TEXT")
                                .HasColumnName("status");

                            b1.HasKey("NotificationId");

                            b1.ToTable("notifications");

                            b1.WithOwner()
                                .HasForeignKey("NotificationId");
                        });

                    b.OwnsOne("LowCortisol.Domain.Contexts.NotificationManagement.ValueObjects.NotificationChannel", "Channel", b1 =>
                        {
                            b1.Property<Guid>("NotificationId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("TEXT")
                                .HasColumnName("channel");

                            b1.HasKey("NotificationId");

                            b1.ToTable("notifications");

                            b1.WithOwner()
                                .HasForeignKey("NotificationId");
                        });

                    b.OwnsOne("LowCortisol.Domain.Contexts.NotificationManagement.ValueObjects.NotificationMessage", "Message", b1 =>
                        {
                            b1.Property<Guid>("NotificationId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasMaxLength(600)
                                .HasColumnType("TEXT")
                                .HasColumnName("body");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("TEXT")
                                .HasColumnName("title");

                            b1.HasKey("NotificationId");

                            b1.ToTable("notifications");

                            b1.WithOwner()
                                .HasForeignKey("NotificationId");
                        });

                    b.Navigation("Channel")
                        .IsRequired();

                    b.Navigation("Message")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.NotificationManagement.Entities.NotificationAttempt", b =>
                {
                    b.HasOne("LowCortisol.Domain.Contexts.NotificationManagement.Aggregates.Notification", null)
                        .WithMany("Attempts")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LowCortisol.Domain.Contexts.NotificationManagement.ValueObjects.NotificationStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("NotificationAttemptId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("TEXT")
                                .HasColumnName("status");

                            b1.HasKey("NotificationAttemptId");

                            b1.ToTable("notification_attempts");

                            b1.WithOwner()
                                .HasForeignKey("NotificationAttemptId");
                        });

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.Reporting.Aggregates.ConsumptionReport", b =>
                {
                    b.OwnsOne("LowCortisol.Domain.Contexts.Reporting.ValueObjects.ConsumptionValue", "TotalGasConsumption", b1 =>
                        {
                            b1.Property<Guid>("ConsumptionReportId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("total_gas_unit");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("total_gas_consumption");

                            b1.HasKey("ConsumptionReportId");

                            b1.ToTable("consumption_reports");

                            b1.WithOwner()
                                .HasForeignKey("ConsumptionReportId");
                        });

                    b.OwnsOne("LowCortisol.Domain.Contexts.Reporting.ValueObjects.ConsumptionValue", "TotalWaterConsumption", b1 =>
                        {
                            b1.Property<Guid>("ConsumptionReportId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("total_water_unit");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("total_water_consumption");

                            b1.HasKey("ConsumptionReportId");

                            b1.ToTable("consumption_reports");

                            b1.WithOwner()
                                .HasForeignKey("ConsumptionReportId");
                        });

                    b.OwnsOne("LowCortisol.Domain.Contexts.Reporting.ValueObjects.ReportPeriod", "Period", b1 =>
                        {
                            b1.Property<Guid>("ConsumptionReportId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("TEXT")
                                .HasColumnName("period");

                            b1.HasKey("ConsumptionReportId");

                            b1.ToTable("consumption_reports");

                            b1.WithOwner()
                                .HasForeignKey("ConsumptionReportId");
                        });

                    b.Navigation("Period")
                        .IsRequired();

                    b.Navigation("TotalGasConsumption")
                        .IsRequired();

                    b.Navigation("TotalWaterConsumption")
                        .IsRequired();
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.Reporting.Entities.ReportLine", b =>
                {
                    b.HasOne("LowCortisol.Domain.Contexts.Reporting.Aggregates.ConsumptionReport", null)
                        .WithMany("Lines")
                        .HasForeignKey("ConsumptionReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LowCortisol.Domain.Contexts.Reporting.ValueObjects.ConsumptionValue", "GasConsumption", b1 =>
                        {
                            b1.Property<Guid>("ReportLineId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("gas_unit");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("gas_consumption");

                            b1.HasKey("ReportLineId");

                            b1.ToTable("report_lines");

                            b1.WithOwner()
                                .HasForeignKey("ReportLineId");
                        });

                    b.OwnsOne("LowCortisol.Domain.Contexts.Reporting.ValueObjects.ConsumptionValue", "WaterConsumption", b1 =>
                        {
                            b1.Property<Guid>("ReportLineId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("water_unit");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("water_consumption");

                            b1.HasKey("ReportLineId");

                            b1.ToTable("report_lines");

                            b1.WithOwner()
                                .HasForeignKey("ReportLineId");
                        });

                    b.Navigation("GasConsumption")
                        .IsRequired();

                    b.Navigation("WaterConsumption")
                        .IsRequired();
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.DeviceManagement.Aggregates.Device", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.IncidentManagement.Aggregates.Incident", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.Monitoring.Aggregates.MonitoringSession", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Readings");
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.NotificationManagement.Aggregates.Notification", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("LowCortisol.Domain.Contexts.Reporting.Aggregates.ConsumptionReport", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
